// Code generated by 'yaegi extract github.com/vgough/sequin/internal/script/runtime'. DO NOT EDIT.

package exports

import (
	"github.com/vgough/sequin/internal/script/runtime"
	"reflect"
)

func init() {
	Symbols["github.com/vgough/sequin/internal/script/runtime/api"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Version": reflect.ValueOf(api.Version),
	}
}
