// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// Operation is the predicate function for operation builders.
type Operation func(*sql.Selector)
