// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/vgough/sequin/storage/ent/label"
	"github.com/vgough/sequin/storage/ent/operation"
	"github.com/vgough/sequin/storage/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeLabel     = "Label"
	TypeOperation = "Operation"
)

// LabelMutation represents an operation that mutates the Label nodes in the graph.
type LabelMutation struct {
	config
	op               Op
	typ              string
	id               *int
	name             *string
	value            *string
	clearedFields    map[string]struct{}
	operation        map[int]struct{}
	removedoperation map[int]struct{}
	clearedoperation bool
	done             bool
	oldValue         func(context.Context) (*Label, error)
	predicates       []predicate.Label
}

var _ ent.Mutation = (*LabelMutation)(nil)

// labelOption allows management of the mutation configuration using functional options.
type labelOption func(*LabelMutation)

// newLabelMutation creates new mutation for the Label entity.
func newLabelMutation(c config, op Op, opts ...labelOption) *LabelMutation {
	m := &LabelMutation{
		config:        c,
		op:            op,
		typ:           TypeLabel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLabelID sets the ID field of the mutation.
func withLabelID(id int) labelOption {
	return func(m *LabelMutation) {
		var (
			err   error
			once  sync.Once
			value *Label
		)
		m.oldValue = func(ctx context.Context) (*Label, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Label.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLabel sets the old Label of the mutation.
func withLabel(node *Label) labelOption {
	return func(m *LabelMutation) {
		m.oldValue = func(context.Context) (*Label, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LabelMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LabelMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LabelMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LabelMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Label.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *LabelMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *LabelMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Label entity.
// If the Label object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabelMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *LabelMutation) ResetName() {
	m.name = nil
}

// SetValue sets the "value" field.
func (m *LabelMutation) SetValue(s string) {
	m.value = &s
}

// Value returns the value of the "value" field in the mutation.
func (m *LabelMutation) Value() (r string, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Label entity.
// If the Label object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabelMutation) OldValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// ResetValue resets all changes to the "value" field.
func (m *LabelMutation) ResetValue() {
	m.value = nil
}

// AddOperationIDs adds the "operation" edge to the Operation entity by ids.
func (m *LabelMutation) AddOperationIDs(ids ...int) {
	if m.operation == nil {
		m.operation = make(map[int]struct{})
	}
	for i := range ids {
		m.operation[ids[i]] = struct{}{}
	}
}

// ClearOperation clears the "operation" edge to the Operation entity.
func (m *LabelMutation) ClearOperation() {
	m.clearedoperation = true
}

// OperationCleared reports if the "operation" edge to the Operation entity was cleared.
func (m *LabelMutation) OperationCleared() bool {
	return m.clearedoperation
}

// RemoveOperationIDs removes the "operation" edge to the Operation entity by IDs.
func (m *LabelMutation) RemoveOperationIDs(ids ...int) {
	if m.removedoperation == nil {
		m.removedoperation = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.operation, ids[i])
		m.removedoperation[ids[i]] = struct{}{}
	}
}

// RemovedOperation returns the removed IDs of the "operation" edge to the Operation entity.
func (m *LabelMutation) RemovedOperationIDs() (ids []int) {
	for id := range m.removedoperation {
		ids = append(ids, id)
	}
	return
}

// OperationIDs returns the "operation" edge IDs in the mutation.
func (m *LabelMutation) OperationIDs() (ids []int) {
	for id := range m.operation {
		ids = append(ids, id)
	}
	return
}

// ResetOperation resets all changes to the "operation" edge.
func (m *LabelMutation) ResetOperation() {
	m.operation = nil
	m.clearedoperation = false
	m.removedoperation = nil
}

// Where appends a list predicates to the LabelMutation builder.
func (m *LabelMutation) Where(ps ...predicate.Label) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LabelMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LabelMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Label, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LabelMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LabelMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Label).
func (m *LabelMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LabelMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, label.FieldName)
	}
	if m.value != nil {
		fields = append(fields, label.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LabelMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case label.FieldName:
		return m.Name()
	case label.FieldValue:
		return m.Value()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LabelMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case label.FieldName:
		return m.OldName(ctx)
	case label.FieldValue:
		return m.OldValue(ctx)
	}
	return nil, fmt.Errorf("unknown Label field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabelMutation) SetField(name string, value ent.Value) error {
	switch name {
	case label.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case label.FieldValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Label field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LabelMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LabelMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabelMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Label numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LabelMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LabelMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LabelMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Label nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LabelMutation) ResetField(name string) error {
	switch name {
	case label.FieldName:
		m.ResetName()
		return nil
	case label.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Label field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LabelMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.operation != nil {
		edges = append(edges, label.EdgeOperation)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LabelMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case label.EdgeOperation:
		ids := make([]ent.Value, 0, len(m.operation))
		for id := range m.operation {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LabelMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedoperation != nil {
		edges = append(edges, label.EdgeOperation)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LabelMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case label.EdgeOperation:
		ids := make([]ent.Value, 0, len(m.removedoperation))
		for id := range m.removedoperation {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LabelMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedoperation {
		edges = append(edges, label.EdgeOperation)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LabelMutation) EdgeCleared(name string) bool {
	switch name {
	case label.EdgeOperation:
		return m.clearedoperation
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LabelMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Label unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LabelMutation) ResetEdge(name string) error {
	switch name {
	case label.EdgeOperation:
		m.ResetOperation()
		return nil
	}
	return fmt.Errorf("unknown Label edge %s", name)
}

// OperationMutation represents an operation that mutates the Operation nodes in the graph.
type OperationMutation struct {
	config
	op            Op
	typ           string
	id            *int
	create_time   *time.Time
	update_time   *time.Time
	request_id    *string
	shard         *int64
	addshard      *int64
	detail        *[]byte
	next_check_at *time.Time
	state         *[]byte
	result        *[]byte
	submitter     *string
	started_at    *time.Time
	finished_at   *time.Time
	clearedFields map[string]struct{}
	labels        map[int]struct{}
	removedlabels map[int]struct{}
	clearedlabels bool
	done          bool
	oldValue      func(context.Context) (*Operation, error)
	predicates    []predicate.Operation
}

var _ ent.Mutation = (*OperationMutation)(nil)

// operationOption allows management of the mutation configuration using functional options.
type operationOption func(*OperationMutation)

// newOperationMutation creates new mutation for the Operation entity.
func newOperationMutation(c config, op Op, opts ...operationOption) *OperationMutation {
	m := &OperationMutation{
		config:        c,
		op:            op,
		typ:           TypeOperation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOperationID sets the ID field of the mutation.
func withOperationID(id int) operationOption {
	return func(m *OperationMutation) {
		var (
			err   error
			once  sync.Once
			value *Operation
		)
		m.oldValue = func(ctx context.Context) (*Operation, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Operation.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOperation sets the old Operation of the mutation.
func withOperation(node *Operation) operationOption {
	return func(m *OperationMutation) {
		m.oldValue = func(context.Context) (*Operation, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OperationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OperationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *OperationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *OperationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Operation.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *OperationMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *OperationMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *OperationMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *OperationMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *OperationMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *OperationMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetRequestID sets the "request_id" field.
func (m *OperationMutation) SetRequestID(s string) {
	m.request_id = &s
}

// RequestID returns the value of the "request_id" field in the mutation.
func (m *OperationMutation) RequestID() (r string, exists bool) {
	v := m.request_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestID returns the old "request_id" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldRequestID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestID: %w", err)
	}
	return oldValue.RequestID, nil
}

// ResetRequestID resets all changes to the "request_id" field.
func (m *OperationMutation) ResetRequestID() {
	m.request_id = nil
}

// SetShard sets the "shard" field.
func (m *OperationMutation) SetShard(i int64) {
	m.shard = &i
	m.addshard = nil
}

// Shard returns the value of the "shard" field in the mutation.
func (m *OperationMutation) Shard() (r int64, exists bool) {
	v := m.shard
	if v == nil {
		return
	}
	return *v, true
}

// OldShard returns the old "shard" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldShard(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldShard is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldShard requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldShard: %w", err)
	}
	return oldValue.Shard, nil
}

// AddShard adds i to the "shard" field.
func (m *OperationMutation) AddShard(i int64) {
	if m.addshard != nil {
		*m.addshard += i
	} else {
		m.addshard = &i
	}
}

// AddedShard returns the value that was added to the "shard" field in this mutation.
func (m *OperationMutation) AddedShard() (r int64, exists bool) {
	v := m.addshard
	if v == nil {
		return
	}
	return *v, true
}

// ResetShard resets all changes to the "shard" field.
func (m *OperationMutation) ResetShard() {
	m.shard = nil
	m.addshard = nil
}

// SetDetail sets the "detail" field.
func (m *OperationMutation) SetDetail(b []byte) {
	m.detail = &b
}

// Detail returns the value of the "detail" field in the mutation.
func (m *OperationMutation) Detail() (r []byte, exists bool) {
	v := m.detail
	if v == nil {
		return
	}
	return *v, true
}

// OldDetail returns the old "detail" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldDetail(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDetail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDetail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDetail: %w", err)
	}
	return oldValue.Detail, nil
}

// ResetDetail resets all changes to the "detail" field.
func (m *OperationMutation) ResetDetail() {
	m.detail = nil
}

// SetNextCheckAt sets the "next_check_at" field.
func (m *OperationMutation) SetNextCheckAt(t time.Time) {
	m.next_check_at = &t
}

// NextCheckAt returns the value of the "next_check_at" field in the mutation.
func (m *OperationMutation) NextCheckAt() (r time.Time, exists bool) {
	v := m.next_check_at
	if v == nil {
		return
	}
	return *v, true
}

// OldNextCheckAt returns the old "next_check_at" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldNextCheckAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNextCheckAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNextCheckAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNextCheckAt: %w", err)
	}
	return oldValue.NextCheckAt, nil
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (m *OperationMutation) ClearNextCheckAt() {
	m.next_check_at = nil
	m.clearedFields[operation.FieldNextCheckAt] = struct{}{}
}

// NextCheckAtCleared returns if the "next_check_at" field was cleared in this mutation.
func (m *OperationMutation) NextCheckAtCleared() bool {
	_, ok := m.clearedFields[operation.FieldNextCheckAt]
	return ok
}

// ResetNextCheckAt resets all changes to the "next_check_at" field.
func (m *OperationMutation) ResetNextCheckAt() {
	m.next_check_at = nil
	delete(m.clearedFields, operation.FieldNextCheckAt)
}

// SetState sets the "state" field.
func (m *OperationMutation) SetState(b []byte) {
	m.state = &b
}

// State returns the value of the "state" field in the mutation.
func (m *OperationMutation) State() (r []byte, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldState(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// ClearState clears the value of the "state" field.
func (m *OperationMutation) ClearState() {
	m.state = nil
	m.clearedFields[operation.FieldState] = struct{}{}
}

// StateCleared returns if the "state" field was cleared in this mutation.
func (m *OperationMutation) StateCleared() bool {
	_, ok := m.clearedFields[operation.FieldState]
	return ok
}

// ResetState resets all changes to the "state" field.
func (m *OperationMutation) ResetState() {
	m.state = nil
	delete(m.clearedFields, operation.FieldState)
}

// SetResult sets the "result" field.
func (m *OperationMutation) SetResult(b []byte) {
	m.result = &b
}

// Result returns the value of the "result" field in the mutation.
func (m *OperationMutation) Result() (r []byte, exists bool) {
	v := m.result
	if v == nil {
		return
	}
	return *v, true
}

// OldResult returns the old "result" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldResult(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResult is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResult requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResult: %w", err)
	}
	return oldValue.Result, nil
}

// ClearResult clears the value of the "result" field.
func (m *OperationMutation) ClearResult() {
	m.result = nil
	m.clearedFields[operation.FieldResult] = struct{}{}
}

// ResultCleared returns if the "result" field was cleared in this mutation.
func (m *OperationMutation) ResultCleared() bool {
	_, ok := m.clearedFields[operation.FieldResult]
	return ok
}

// ResetResult resets all changes to the "result" field.
func (m *OperationMutation) ResetResult() {
	m.result = nil
	delete(m.clearedFields, operation.FieldResult)
}

// SetSubmitter sets the "submitter" field.
func (m *OperationMutation) SetSubmitter(s string) {
	m.submitter = &s
}

// Submitter returns the value of the "submitter" field in the mutation.
func (m *OperationMutation) Submitter() (r string, exists bool) {
	v := m.submitter
	if v == nil {
		return
	}
	return *v, true
}

// OldSubmitter returns the old "submitter" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldSubmitter(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubmitter is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubmitter requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubmitter: %w", err)
	}
	return oldValue.Submitter, nil
}

// ResetSubmitter resets all changes to the "submitter" field.
func (m *OperationMutation) ResetSubmitter() {
	m.submitter = nil
}

// SetStartedAt sets the "started_at" field.
func (m *OperationMutation) SetStartedAt(t time.Time) {
	m.started_at = &t
}

// StartedAt returns the value of the "started_at" field in the mutation.
func (m *OperationMutation) StartedAt() (r time.Time, exists bool) {
	v := m.started_at
	if v == nil {
		return
	}
	return *v, true
}

// OldStartedAt returns the old "started_at" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldStartedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartedAt: %w", err)
	}
	return oldValue.StartedAt, nil
}

// ClearStartedAt clears the value of the "started_at" field.
func (m *OperationMutation) ClearStartedAt() {
	m.started_at = nil
	m.clearedFields[operation.FieldStartedAt] = struct{}{}
}

// StartedAtCleared returns if the "started_at" field was cleared in this mutation.
func (m *OperationMutation) StartedAtCleared() bool {
	_, ok := m.clearedFields[operation.FieldStartedAt]
	return ok
}

// ResetStartedAt resets all changes to the "started_at" field.
func (m *OperationMutation) ResetStartedAt() {
	m.started_at = nil
	delete(m.clearedFields, operation.FieldStartedAt)
}

// SetFinishedAt sets the "finished_at" field.
func (m *OperationMutation) SetFinishedAt(t time.Time) {
	m.finished_at = &t
}

// FinishedAt returns the value of the "finished_at" field in the mutation.
func (m *OperationMutation) FinishedAt() (r time.Time, exists bool) {
	v := m.finished_at
	if v == nil {
		return
	}
	return *v, true
}

// OldFinishedAt returns the old "finished_at" field's value of the Operation entity.
// If the Operation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OperationMutation) OldFinishedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFinishedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFinishedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFinishedAt: %w", err)
	}
	return oldValue.FinishedAt, nil
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (m *OperationMutation) ClearFinishedAt() {
	m.finished_at = nil
	m.clearedFields[operation.FieldFinishedAt] = struct{}{}
}

// FinishedAtCleared returns if the "finished_at" field was cleared in this mutation.
func (m *OperationMutation) FinishedAtCleared() bool {
	_, ok := m.clearedFields[operation.FieldFinishedAt]
	return ok
}

// ResetFinishedAt resets all changes to the "finished_at" field.
func (m *OperationMutation) ResetFinishedAt() {
	m.finished_at = nil
	delete(m.clearedFields, operation.FieldFinishedAt)
}

// AddLabelIDs adds the "labels" edge to the Label entity by ids.
func (m *OperationMutation) AddLabelIDs(ids ...int) {
	if m.labels == nil {
		m.labels = make(map[int]struct{})
	}
	for i := range ids {
		m.labels[ids[i]] = struct{}{}
	}
}

// ClearLabels clears the "labels" edge to the Label entity.
func (m *OperationMutation) ClearLabels() {
	m.clearedlabels = true
}

// LabelsCleared reports if the "labels" edge to the Label entity was cleared.
func (m *OperationMutation) LabelsCleared() bool {
	return m.clearedlabels
}

// RemoveLabelIDs removes the "labels" edge to the Label entity by IDs.
func (m *OperationMutation) RemoveLabelIDs(ids ...int) {
	if m.removedlabels == nil {
		m.removedlabels = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.labels, ids[i])
		m.removedlabels[ids[i]] = struct{}{}
	}
}

// RemovedLabels returns the removed IDs of the "labels" edge to the Label entity.
func (m *OperationMutation) RemovedLabelsIDs() (ids []int) {
	for id := range m.removedlabels {
		ids = append(ids, id)
	}
	return
}

// LabelsIDs returns the "labels" edge IDs in the mutation.
func (m *OperationMutation) LabelsIDs() (ids []int) {
	for id := range m.labels {
		ids = append(ids, id)
	}
	return
}

// ResetLabels resets all changes to the "labels" edge.
func (m *OperationMutation) ResetLabels() {
	m.labels = nil
	m.clearedlabels = false
	m.removedlabels = nil
}

// Where appends a list predicates to the OperationMutation builder.
func (m *OperationMutation) Where(ps ...predicate.Operation) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the OperationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *OperationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Operation, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *OperationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *OperationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Operation).
func (m *OperationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OperationMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.create_time != nil {
		fields = append(fields, operation.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, operation.FieldUpdateTime)
	}
	if m.request_id != nil {
		fields = append(fields, operation.FieldRequestID)
	}
	if m.shard != nil {
		fields = append(fields, operation.FieldShard)
	}
	if m.detail != nil {
		fields = append(fields, operation.FieldDetail)
	}
	if m.next_check_at != nil {
		fields = append(fields, operation.FieldNextCheckAt)
	}
	if m.state != nil {
		fields = append(fields, operation.FieldState)
	}
	if m.result != nil {
		fields = append(fields, operation.FieldResult)
	}
	if m.submitter != nil {
		fields = append(fields, operation.FieldSubmitter)
	}
	if m.started_at != nil {
		fields = append(fields, operation.FieldStartedAt)
	}
	if m.finished_at != nil {
		fields = append(fields, operation.FieldFinishedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OperationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case operation.FieldCreateTime:
		return m.CreateTime()
	case operation.FieldUpdateTime:
		return m.UpdateTime()
	case operation.FieldRequestID:
		return m.RequestID()
	case operation.FieldShard:
		return m.Shard()
	case operation.FieldDetail:
		return m.Detail()
	case operation.FieldNextCheckAt:
		return m.NextCheckAt()
	case operation.FieldState:
		return m.State()
	case operation.FieldResult:
		return m.Result()
	case operation.FieldSubmitter:
		return m.Submitter()
	case operation.FieldStartedAt:
		return m.StartedAt()
	case operation.FieldFinishedAt:
		return m.FinishedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OperationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case operation.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case operation.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case operation.FieldRequestID:
		return m.OldRequestID(ctx)
	case operation.FieldShard:
		return m.OldShard(ctx)
	case operation.FieldDetail:
		return m.OldDetail(ctx)
	case operation.FieldNextCheckAt:
		return m.OldNextCheckAt(ctx)
	case operation.FieldState:
		return m.OldState(ctx)
	case operation.FieldResult:
		return m.OldResult(ctx)
	case operation.FieldSubmitter:
		return m.OldSubmitter(ctx)
	case operation.FieldStartedAt:
		return m.OldStartedAt(ctx)
	case operation.FieldFinishedAt:
		return m.OldFinishedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Operation field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OperationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case operation.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case operation.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case operation.FieldRequestID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestID(v)
		return nil
	case operation.FieldShard:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetShard(v)
		return nil
	case operation.FieldDetail:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDetail(v)
		return nil
	case operation.FieldNextCheckAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNextCheckAt(v)
		return nil
	case operation.FieldState:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case operation.FieldResult:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResult(v)
		return nil
	case operation.FieldSubmitter:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubmitter(v)
		return nil
	case operation.FieldStartedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartedAt(v)
		return nil
	case operation.FieldFinishedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFinishedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Operation field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OperationMutation) AddedFields() []string {
	var fields []string
	if m.addshard != nil {
		fields = append(fields, operation.FieldShard)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OperationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case operation.FieldShard:
		return m.AddedShard()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OperationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case operation.FieldShard:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddShard(v)
		return nil
	}
	return fmt.Errorf("unknown Operation numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OperationMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(operation.FieldNextCheckAt) {
		fields = append(fields, operation.FieldNextCheckAt)
	}
	if m.FieldCleared(operation.FieldState) {
		fields = append(fields, operation.FieldState)
	}
	if m.FieldCleared(operation.FieldResult) {
		fields = append(fields, operation.FieldResult)
	}
	if m.FieldCleared(operation.FieldStartedAt) {
		fields = append(fields, operation.FieldStartedAt)
	}
	if m.FieldCleared(operation.FieldFinishedAt) {
		fields = append(fields, operation.FieldFinishedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OperationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OperationMutation) ClearField(name string) error {
	switch name {
	case operation.FieldNextCheckAt:
		m.ClearNextCheckAt()
		return nil
	case operation.FieldState:
		m.ClearState()
		return nil
	case operation.FieldResult:
		m.ClearResult()
		return nil
	case operation.FieldStartedAt:
		m.ClearStartedAt()
		return nil
	case operation.FieldFinishedAt:
		m.ClearFinishedAt()
		return nil
	}
	return fmt.Errorf("unknown Operation nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OperationMutation) ResetField(name string) error {
	switch name {
	case operation.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case operation.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case operation.FieldRequestID:
		m.ResetRequestID()
		return nil
	case operation.FieldShard:
		m.ResetShard()
		return nil
	case operation.FieldDetail:
		m.ResetDetail()
		return nil
	case operation.FieldNextCheckAt:
		m.ResetNextCheckAt()
		return nil
	case operation.FieldState:
		m.ResetState()
		return nil
	case operation.FieldResult:
		m.ResetResult()
		return nil
	case operation.FieldSubmitter:
		m.ResetSubmitter()
		return nil
	case operation.FieldStartedAt:
		m.ResetStartedAt()
		return nil
	case operation.FieldFinishedAt:
		m.ResetFinishedAt()
		return nil
	}
	return fmt.Errorf("unknown Operation field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OperationMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.labels != nil {
		edges = append(edges, operation.EdgeLabels)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OperationMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case operation.EdgeLabels:
		ids := make([]ent.Value, 0, len(m.labels))
		for id := range m.labels {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OperationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedlabels != nil {
		edges = append(edges, operation.EdgeLabels)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OperationMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case operation.EdgeLabels:
		ids := make([]ent.Value, 0, len(m.removedlabels))
		for id := range m.removedlabels {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OperationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedlabels {
		edges = append(edges, operation.EdgeLabels)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OperationMutation) EdgeCleared(name string) bool {
	switch name {
	case operation.EdgeLabels:
		return m.clearedlabels
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OperationMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Operation unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OperationMutation) ResetEdge(name string) error {
	switch name {
	case operation.EdgeLabels:
		m.ResetLabels()
		return nil
	}
	return fmt.Errorf("unknown Operation edge %s", name)
}
